object_dataset:
    class_name: "ImageNetObjectDataset"
    root_dir: "/global/cfs/cdirs/m5073/ptycho_simulation_factory/data/raw/winter21_whole"
    # Range from which the min magnitude of the object is drawn. The magnitude
    # of a generated object is in the range of [min_mag, 1].
    random_min_mag_range: [0.8, 0.98]
    # Range from which the phase of the object is drawn. The phase of a generated
    # object is in the range of [-phase_range / 2, phase_range / 2].
    random_phase_range: [0.8, 1.8]

probe_dataset:
    class_name: "NpyProbeDataset"
    root_dir: "/global/cfs/cdirs/m5073/synaps_data/probes"
    # Output shape of the probe. Original shape is preserved if null.
    output_shape: [256, 256]
    remove_opr_modes: true
    random_defocus_range_m: [-1.0e-4, 1.0e-4]
    energy_for_defocusing_kev: 10
    pixel_size_for_defocusing_m: 1.0e-8
    # The csv file containing the name-sampling probability map. The first column
    # is the basenames of probe files (e.g., "velociprobe_fly001.npy"), and the
    # second column is the sampling probability. The names in the map are used as the
    # index for the dataset.
    name_probability_map_file: "/global/cfs/cdirs/m5073/synaps_data/probes/name_probability_map.csv"

position_generator:
    class_name: "RasterGridGenerator"
    spacing_x: 10
    spacing_y: 10

simulator:
    pixel_size_m: 1.0e-8
    energy_kev: 10
    add_poisson_noise: false
    # Total photon count of diffraction patterns for adding Poisson noise.
    total_photon_count: 100000

task:
    output_root: "../synaps_data/simulated_data"
