object_dataset:
    class_name: "ImageNetObjectDataset"
    root_dir: "/scratch/ptycho_simulation_factory/data/raw/winter21_whole"
    # Range from which the min magnitude of the object is drawn. The magnitude
    # of a generated object is in the range of [min_mag, 1].
    random_min_mag_range: [0.8, 0.98]
    # Range from which the phase of the object is drawn. The phase of a generated
    # object is in the range of [-phase_range / 2, phase_range / 2].
    random_phase_range: [0.8, 1.8]

probe_dataset:
    class_name: "NpyProbeDataset"
    root_dir: "/scratch/synaps_data/probes"
    # Output shape of the probe. Original shape is preserved if null.
    output_shape: [256, 256]
    remove_opr_modes: true

position_generator:
    class_name: "RasterGridGenerator"
    spacing_x: 10
    spacing_y: 10

simulator:
    pixel_size_m: 1.0e-8
    energy_kev: 10
    add_poisson_noise: false
    # Total photon count of diffraction patterns for adding Poisson noise.
    total_photon_count: 100000

task:
    output_root: "output/"
